name: Github AWS OIDC

on:
  push:
    branches: [gc-aws-oidc-test]

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials for Singapore Region using OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          # audience: sts.amazonaws.com
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}

      - name: Test AWS Credentials
        # run: aws sts get-caller-identity
        run: aws iam get-role --role-name Github-Actions-Role
