name: Github AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    name: OIDC Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials for Singapore Region using OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          # audience: sts.amazonaws.com
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.0"

      - name: Terraform Init
        run: terraform init
        working-directory: ./tf

      - name: Terraform Format Check
        run: terraform fmt
        working-directory: ./tf

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./tf

      - name: Terraform Plan
        run: terraform plan

      # Dangerous! Need gatekeeping here.
      # This is just a test.
      - name: Terraform Apply
        run: terraform apply -auto-approve
    
      # - name: Test AWS Credentials
      #   run: aws sts get-caller-identity
