name: Github AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    name: OIDC Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials for Singapore Region using OIDC
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          # audience: sts.amazonaws.com
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_OIDC_IAM_ROLE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@latest
        with:
          terraform_version: "1.14.0"

      - name: Terraform Init
        run: terraform init
        working_directory: tf

      - name: Terraform Format Check
        run: terraform fmt
        working_directory: tf

      - name: Terraform Validate
        run: terraform validate
        working_directory: tf
    
      # - name: Test AWS Credentials
      #   run: aws sts get-caller-identity
